import { faker } from "@faker-js/faker";

const products = [
  {
    id: faker.random.numeric(5),
    name: "iphone 13",
    model: "Navy Blue",
    imgURL: require("./assets/images/iphone-13-dark-blue.png"),
    rate: faker.datatype.number({ max: 10 }) / 2,
    price: faker.commerce.price(),
    description: faker.random.words(200),
  },
  {
    id: faker.random.numeric(5),
    name: "iphone 13 pro",
    model: "Grey",
    imgURL: require("./assets/images/iphone-13-pro-max-black.png"),
    rate: faker.datatype.number({ max: 10 }) / 2,
    price: faker.commerce.price(),
    description: faker.random.words(200),
  },
  {
    id: faker.random.numeric(5),
    name: "iphone 13 pro",
    model: "Sierra Blue",
    imgURL: require("./assets/images/iphone-13-pro-max.png"),
    rate: faker.datatype.number({ max: 10 }) / 2,
    price: faker.commerce.price(),
    description: faker.random.words(200),
  },
  {
    id: faker.random.numeric(5),
    name: "iphone 13",
    model: "White",
    imgURL: require("./assets/iphone-13-white.png"),
    rate: faker.datatype.number({ max: 10 }) / 2,
    price: faker.commerce.price(),
    description: faker.random.words(200),
  },
  {
    id: faker.random.numeric(5),
    name: "iphone 13",
    model: "Rose",
    imgURL: require("./assets/iphone-13.png"),
    rate: faker.datatype.number({ max: 10 }) / 2,
    price: faker.commerce.price(),
    description: faker.random.words(200),
  },
  {
    id: faker.random.numeric(5),
    name: "Mackbook",
    model: "Silver",
    imgURL: require("./assets/macbook.png"),
    rate: faker.datatype.number({ max: 10 }) / 2,
    price: faker.commerce.price(),
    description: faker.random.words(200),
  },
  {
    id: faker.random.numeric(5),
    name: "Note-20-ultra",
    model: "2-options",
    imgURL: require("./assets/note-20-ultra.png"),
    rate: faker.datatype.number({ max: 10 }) / 2,
    price: faker.commerce.price(),
    description: faker.random.words(200),
  },
  {
    id: faker.random.numeric(5),
    name: "s22-plus",
    model: "Silver",
    imgURL: require("./assets/s22-plus.png"),
    rate: faker.datatype.number({ max: 10 }) / 2,
    price: faker.commerce.price(),
    description: faker.random.words(200),
  },
  {
    id: faker.random.numeric(5),
    name: "s22-ultra-5g",
    model: "Silver",
    imgURL: require("./assets/s22-ultra-5g.png"),
    rate: faker.datatype.number({ max: 10 }) / 2,
    price: faker.commerce.price(),
    description: faker.random.words(200),
  },
];

export default products;
