import { faker } from "@faker-js/faker";

const products = [
  {
    id: faker.random.numeric(5),
    name: "iphone 13",
    model: "Navy Blue",
    imgURL: require("./assets/images/iphone-13-dark-blue.png"),
    computer: false,
    rate: faker.datatype.number({ max: 10 }) / 2,
    price: faker.commerce.price(),
    description: faker.random.words(200),
  },
  {
    id: faker.random.numeric(5),
    name: "iphone 13 pro",
    model: "Grey",
    imgURL: require("./assets/images/iphone-13-pro-max-black.png"),
    computer: false,
    rate: faker.datatype.number({ max: 10 }) / 2,
    price: faker.commerce.price(),
    description: faker.random.words(200),
  },
  {
    id: faker.random.numeric(5),
    name: "iphone 13 pro",
    model: "Sierra Blue",
    imgURL: require("./assets/images/iphone-13-pro-max.png"),
    computer: false,
    rate: faker.datatype.number({ max: 10 }) / 2,
    price: faker.commerce.price(),
    description: faker.random.words(200),
  },
  {
    id: faker.random.numeric(5),
    name: "iphone 13",
    model: "White",
    imgURL: require("./assets/images/iphone-13-white.png"),
    computer: false,
    rate: faker.datatype.number({ max: 10 }) / 2,
    price: faker.commerce.price(),
    description: faker.random.words(200),
  },
  {
    id: faker.random.numeric(5),
    name: "Mackbook",
    model: "Silver",
    imgURL: require("./assets/images/mackbook.png"),
    computer: true,
    rate: faker.datatype.number({ max: 10 }) / 2,
    price: faker.commerce.price(),
    description: faker.random.words(200),
  },
  {
    id: faker.random.numeric(5),
    name: "iphone 13",
    model: "Rose",
    imgURL: require("./assets/images/iphone-13.png"),
    computer: false,
    rate: faker.datatype.number({ max: 10 }) / 2,
    price: faker.commerce.price(),
    description: faker.random.words(200),
  },

  {
    id: faker.random.numeric(5),
    name: "Note-20-ultra",
    model: "2-options",
    imgURL: require("./assets/images/note-20-ultra.png"),
    computer: false,
    rate: faker.datatype.number({ max: 10 }) / 2,
    price: faker.commerce.price(),
    description: faker.random.words(200),
  },
  {
    id: faker.random.numeric(5),
    name: "s22-plus",
    model: "Silver",
    imgURL: require("./assets/images/s22-plus.png"),
    computer: false,
    rate: faker.datatype.number({ max: 10 }) / 2,
    price: faker.commerce.price(),
    description: faker.random.words(200),
  },
  {
    id: faker.random.numeric(5),
    name: "s22-ultra-5g",
    model: "Silver",
    imgURL: require("./assets/images/s22-ultra-5g.png"),
    computer: false,
    rate: faker.datatype.number({ max: 10 }) / 2,
    price: faker.commerce.price(),
    description: faker.random.words(200),
  },
  {
    id: faker.random.numeric(5),
    name: "Dell XPS 15 2-in-1",
    model: "Midnight Gray",
    imgURL: require("./assets/images/dell-black.png"),

    computer: true,
    rate: faker.datatype.number({ max: 10 }) / 2,
    price: faker.commerce.price(),
    description: faker.random.words(200),
  },
  {
    id: faker.random.numeric(5),
    name: "Dell XPS 15",
    model: "Light Grey",
    imgURL: require("./assets/images/dell-gray.png"),
    computer: true,
    rate: faker.datatype.number({ max: 10 }) / 2,
    price: faker.commerce.price(),
    description: faker.random.words(200),
  },
  {
    id: faker.random.numeric(5),
    name: "Sony ZX330BT",
    model: "Light Grey",
    imgURL: require("./assets/images/headphone.png"),
    computer: false,
    rate: faker.datatype.number({ max: 10 }) / 2,
    price: faker.commerce.price(),
    description: faker.random.words(200),
  },
  {
    id: faker.random.numeric(5),
    name: "Iphone 11",
    model: "Subway Blue",
    imgURL: require("./assets/images/iphone-11-green.png"),
    computer: false,
    rate: faker.datatype.number({ max: 10 }) / 2,
    price: faker.commerce.price(),
    description: faker.random.words(200),
  },
  {
    id: faker.random.numeric(5),
    name: "Iphone 11",
    model: "Product RED",
    imgURL: require("./assets/images/iphone-11-red.png"),
    computer: false,
    rate: faker.datatype.number({ max: 10 }) / 2,
    price: faker.commerce.price(),
    description: faker.random.words(200),
  },
  {
    id: faker.random.numeric(5),
    name: "Iphone 11",
    model: "Milky White",
    imgURL: require("./assets/images/iphone-11-white.png"),
    computer: false,
    rate: faker.datatype.number({ max: 10 }) / 2,
    price: faker.commerce.price(),
    description: faker.random.words(200),
  },
  {
    id: faker.random.numeric(5),
    name: "Iphone 11",
    model: "Serious Black",
    imgURL: require("./assets/images/iphone-11.png"),
    computer: false,
    rate: faker.datatype.number({ max: 10 }) / 2,
    price: faker.commerce.price(),
    description: faker.random.words(200),
  },
];

export default products;
