import { faker } from "@faker-js/faker";

const products = [
  {
    id: faker.random.numeric(5),
    name: "Apple Watch",
    model: "Series 5 SE",
    imgURL: require("./assets/images/apple-watch.png"),
    rate: faker.datatype.number({ max: 10 }) / 2,
    price: faker.commerce.price(),
    description: faker.random.words(200),
  },
  {
    id: faker.random.numeric(5),
    name: "Dell XPS 15 2-in-1",
    model: "Midnight Gray",
    imgURL: require("./assets/images/dell-black.png"),
    rate: faker.datatype.number({ max: 10 }) / 2,
    price: faker.commerce.price(),
    description: faker.random.words(200),
  },
  {
    id: faker.random.numeric(5),
    name: "Dell XPS 15",
    model: "Light Grey",
    imgURL: require("./assets/images/dell-gray.png"),
    rate: faker.datatype.number({ max: 10 }) / 2,
    price: faker.commerce.price(),
    description: faker.random.words(200),
  },
  {
    id: faker.random.numeric(5),
    name: "Sony ZX330BT",
    model: "Light Grey",
    imgURL: require("./assets/images/headphone.png"),
    rate: faker.datatype.number({ max: 10 }) / 2,
    price: faker.commerce.price(),
    description: faker.random.words(200),
  },
  {
    id: faker.random.numeric(5),
    name: "Iphone 11",
    model: "Subway Blue",
    imgURL: require("./assets/images/iphone-11-green.png"),
    rate: faker.datatype.number({ max: 10 }) / 2,
    price: faker.commerce.price(),
    description: faker.random.words(200),
  },
  {
    id: faker.random.numeric(5),
    name: "Iphone 11",
    model: "Product RED",
    imgURL: require("./assets/images/iphone-11-red.png"),
    rate: faker.datatype.number({ max: 10 }) / 2,
    price: faker.commerce.price(),
    description: faker.random.words(200),
  },
  {
    id: faker.random.numeric(5),
    name: "Iphone 11",
    model: "Milky White",
    imgURL: require("./assets/images/iphone-11-white.png"),
    rate: faker.datatype.number({ max: 10 }) / 2,
    price: faker.commerce.price(),
    description: faker.random.words(200),
  },
  {
    id: faker.random.numeric(5),
    name: "Iphone 11",
    model: "Serious Black",
    imgURL: require("./assets/images/iphone-11.png"),
    rate: faker.datatype.number({ max: 10 }) / 2,
    price: faker.commerce.price(),
    description: faker.random.words(200),
  },
];

export default products;
